.\"
.\" autobenchd man page - Copyright (2002) Julian T. J. Midgley <jtjm@xenoclast.org>
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.TH AUTOBENCHD 1 "October 14, 2002" "" ""
.SH NAME
autobenchd \- distributed autobench daemon
.SH SYNOPSIS
.nh
.B autobenchd 
.RB [ --port  
.IR port ] 
.RB [ --bindaddr 
.IR bindaddr ]
.RB [ --verbose ] 
.RB [ --debug ]
.br 
.hy 12
.SH DESCRIPTION
.B autobenchd
listens on the port and IP address specified on the command line
(defaulting to port 4600 and INADDR_ANY if the command line options
are omitted), and waits for commands from \fBautobench_admin\fR.  When
it receives these commands, it conducts a benchmark using httperf with
the arguments specified by
.B autobench_admin\fR, parses the httperf results and returns a summary to
\fBautobench_admin\fR.
.B autobench_admin 
collates the results from several instances of 
.B autobenchd 
running on different machines, and writes the collated results to a
file for analysis.
.SH OPTIONS
.TP
.B --port \fIport\fR
Listen on port \fIport\fR. Defaults to 4600 if omitted.
.TP
.B --bindaddr \fIbindaddr\fR
Bind to the address \fIbindaddr\fR, which may be given as either an IP
address or hostname.  INADDR_ANY may be specified as `0.0.0.0\'.
Defaults to INADDR_ANY if omitted.
.TP
.B --verbose
Enable verbose output, which logs progress to stderr (perhaps --speak
would be a better name, since \fBautobenchd\fR is completely silent in normal
operation).
.TP
.B --debug
Send additional debugging output to stderr, including the raw results
returned by httperf.
.SH EXAMPLE
.TP
.nh
autobenchd --port 1234 --bindaddr 123.123.123.213 --verbose
.hy 12
Starts
.B autobenchd 
on port 1234, bound to 123.123.123.213, with progress reporting
enabled.
.SH SEE ALSO
.B autobench_admin\fR(1), 
.B httperf\fR(1)
.SH AUTHOR
Julian T. J. Midgley <jtjm@xenoclast.org>
